# -*- coding: utf-8 -*-
"""MapaPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14JL74BpHR8HOFwVyQwVCOopTsnhAt0zS
"""

import folium

from folium.plugins import minimap
Egipto = folium.Map(location=(26.538776130372437, 29.804375101019836))
Egipto

from folium.plugins import MiniMap
from branca.element import Figure

popuptext = '<b>Heredia</b>'

my_map = folium.Map(location=[10.2856822, -84.9008912], zoom_start=16, titles='stamenterrain')

folium.Marker(location=[10.2856822, -84.9008912], popup=popuptext, icon=folium.Icon(color="orange", icon="ok-sign")).add_to(my_map)

folium.Circle(location=[10.2856822, -84.9008912], color="purple", weigth=6, fill_color="red", fill_opacity=0.5, tooltip='Heredia').add_to(my_map)

minimap = MiniMap(title_layer='stamenterrain', position='bottomright')

my_map.add_child(minimap)

my_map.save('C:folium.html')
my_map

from folium.plugins import MiniMap
from branca.element import Figure

popuptext = '<b>Escuela de Informática</b>'

my_map = folium.Map(location=[9.970775, -84.129122], zoom_start=16, titles='stamenterrain')

folium.Marker(location=[9.970775, -84.129122], popup=popuptext, icon=folium.Icon(color="orange", icon="ok-sign")).add_to(my_map)

folium.Circle(location=[9.970775, -84.129122], color="purple", weigth=6, fill_color="red", fill_opacity=0.5, tooltip='Escuela de Informática').add_to(my_map)

minimap = MiniMap(title_layer='stamenterrain', position='bottomright')

my_map.add_child(minimap)

my_map.save('C:folium.html')
my_map

fig = Figure(width=1000, height=500)
fig.add_child(my_map)
fig